;;Exercise 1.9
;;Each of the following two procedures defines
;;a method for adding two positive integers in terms of the
;;procedures inc, which increments its argument by 1, and dec,
;;which decrements its argument by 1.

;;procedure A
(define (+ a b)
  (if (= a 0) b (inc (+ (dec a) b))))

;;procedure B
(define (+ a b)
  (if (= a 0) b (+ (dec a) (inc b))))

;;Using the substitution model, illustrate the process generated by
;;each procedure in evaluating (+ 4 5) . Are these processes iterative or recursive?


;;Solution
;;procedure A describes a linear recursive process because
;;the number of steps required grows linearly with a.

;;process generated by procedure A:
(inc (+ 3 5))
(inc (inc (+ 2 5)))
(inc (inc (inc (+ 1 5))))
(inc (inc (inc (inc (+ 0 5)))))
(inc (inc (inc 5)))
(inc (inc 6))
(inc 7)
8

;;procedure B descibes a linear iterative process

;;process generated by procedure B:
(+ 4 5)
(+ (dec 4) (inc 5))
(+ (dec 3) (inc 6))
(+ (dec 2) (inc 7))
(+ (dec 1) (inc 8))
(+ 0 9)
9
